// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHYsrHFG6FwSQaTRn4nKbHliE6RKpjLEk',
    appId: '1:370210536267:web:21c996c16ce8c80f3e46ce',
    messagingSenderId: '370210536267',
    projectId: 'tik-tok-alkain77',
    authDomain: 'tik-tok-alkain77.firebaseapp.com',
    storageBucket: 'tik-tok-alkain77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhb9mJ___Fqr1wTtH2ieufHdLdXs3yUYc',
    appId: '1:370210536267:android:5d58691bed6b6d323e46ce',
    messagingSenderId: '370210536267',
    projectId: 'tik-tok-alkain77',
    storageBucket: 'tik-tok-alkain77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5D5_zfLRbtzh61JGIH2gFopW7cZ9EBs0',
    appId: '1:370210536267:ios:960a18d72469a4e63e46ce',
    messagingSenderId: '370210536267',
    projectId: 'tik-tok-alkain77',
    storageBucket: 'tik-tok-alkain77.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
